DATASET:
  # DATA_ROOT: /data/data2/zhk218/data/HSIs/h5
  DATA_ROOT: /home/ren/hkzhang/data
  DATA_SET: PaviaU
  CATEGORY_NUM: 9
  CROP_SIZE: 32
  PATCHES_NUM: 4000
  TRAIN_NUM: 40
  VAL_NUM: 10
SEARCH:
  TIE_CELL: False
SOLVER:
  TRAIN:
    MAX_ITER: 600000
  CHECKPOINT_PERIOD: 500
  VALIDATE_PERIOD: 500
DATALOADER:
  NUM_WORKERS: 4
  BATCH_SIZE_TRAIN: 12
  BATCH_SIZE_TEST: 12
MODEL:
  FILTER_MULTIPLIER: 16
  META_ARCHITECTURE: HSI_compnet
  META_MODE: Width
  NUM_STRIDES: 3
  NUM_LAYERS: 2
  NUM_BLOCKS: 3
  PRIMITIVES: "HSI_AD"
  ACTIVATION_F: "Leaky"
  USE_ASPP: True

OUTPUT_DIR: output

