DATASET:
  # DATA_ROOT: /data/data2/zhk218/data/HSIs/h5
  DATA_ROOT: /home/ren/hkzhang/data
  DATA_SET: Pavia
  CATEGORY_NUM: 9
  CROP_SIZE: 32
  MULTI_SCALE: False
  MCROP_SIZE: [16, 32, 48]
  OVERLAP: False
  TRAIN_NUM: 40
  VAL_NUM: 10
SEARCH:
  TIE_CELL: False
DATALOADER:
  BATCH_SIZE_TEST: 2
MODEL:
  FILTER_MULTIPLIER: 16
  META_ARCHITECTURE: HSI_compnet
  META_MODE: Width
  NUM_STRIDES: 3
  NUM_LAYERS: 2
  NUM_BLOCKS: 3
  PRIMITIVES: "HSI_AD"
  ACTIVATION_F: "Leaky"
  USE_ASPP: True

OUTPUT_DIR: output_ad

